name: Build Jenkins Plugin

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean install --batch-mode -Djava.level=8
      - name: Archive hpi
        uses: actions/upload-artifact@v2
        with:
          name: scm-filter-branch-pr.hpi
          path: target/scm-filter-branch-pr.hpi
