name: Build Jenkins Plugin Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: |
          VERSION=$(echo ${GITHUB_REF##*/} | awk -F '-' '{ print $NF }')
          mvn clean install --batch-mode -Djava.level=8 -Dversion=$VERSION
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/scm-filter-branch-pr.hpi
